# Uncomment the next line to define a global platform for your project
platform :tvos, '12.0'

target 'cocoa-tv' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoa-tv
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'beta'
end
