# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'


target 'cocoa-multi (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoa-multi (iOS)
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'beta'
end

target 'cocoa-multi (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :osx, '11.6'
  # Pods for cocoa-multi (macOS)
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'beta'
end
