# Uncomment the next line to define a global platform for your project
platform :watchos, '6.2'

target 'cocoa-watch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoa-watch
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'beta'
end

target 'cocoa-watch WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoa-watch WatchKit App
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'beta'
end

target 'cocoa-watch WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoa-watch WatchKit Extension
  pod 'Auth0', :git => 'https://github.com/auth0/Auth0.swift.git', :branch => 'beta'
end
